# Generated by Django 2.1.7 on 2020-04-21 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='书名')),
                ('num', models.IntegerField(verbose_name='编号')),
                ('status', models.SmallIntegerField(blank=True, choices=[[0, 'wish'], [1, 'read']], default=0, null=True, verbose_name='想看/已看')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '读书',
                'verbose_name_plural': '读书',
                'db_table': 'tb_book',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
