# Generated by Django 2.1.7 on 2020-04-20 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200420_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
                'db_table': 'tb_article_vote',
            },
        ),
        migrations.CreateModel(
            name='CommentsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(blank=True, default=0, null=True)),
                ('down', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='articles.Comments')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'tb_comments_vote',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='articlevote',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='articles.Article'),
        ),
    ]
